
system_parameters:
  working_directory: '/nas0/ayoub/Impicit-Solvent-DDM/'
  executable: "sander.MPI" # executable machine for MD choice : [sander, sander.MPI, pmemed, pemed.MPI, pmeded.CUDA]
  mpi_command: srun # system dependent /

endstate_parameter_files:
  complex_parameter_filename: structs/complex/cb7-mol01.parm7 # list of topology file of a complex
  complex_coordinate_filename: structs/complex/cb7-mol01.rst7 # list of coordinate file of a complex  

number_of_cores_per_system:
  complex_ncores: 2 #total number of cores per job
  ligand_ncores: 1 #total number of cores per ligand simulation
  receptor_ncores: 1 #total number of cores per ligand simulation

AMBER_masks:
  receptor_mask: ':CB7' # list of Amber masks denoting receptor atoms in respected complex file
  ligand_mask: ':M01' # list of Amber masks denoting ligand atoms in respected complex file


workflow:
  endstate_method: remd #options REMD, MD or 0 (meaning no endstate simulation will be performed just intermidates)endstate_method: REMD #options REMD, MD or 0 (meaning no endstate simulation will be performed just intermidates) 
  endstate_arguments:
    flat_bottom_restraints: {r1: 0, r2: 0, r3: 10, r4: 20, rk2: 0.1, rk3: 0.1} #r1, r2, r3, r4, rk2, rk3
    flat_bottom_restraint_filename: #optional  
    nthreads_complex: 4
    nthreads_receptor: 4
    nthreads_ligand: 4
    ngroups: 4 
    target_temperature: 298
    equilibration_replica_mdins: [equilibration_mdin/mdin.rep.001, equilibration_mdin/mdin.rep.002, equilibration_mdin/mdin.rep.003, equilibration_mdin/mdin.rep.004]
    remd_mdins: [remd_mdins/remd.mdin.001, remd_mdins/remd.mdin.002, remd_mdins/remd.mdin.003, remd_mdins/remd.mdin.004]

  intermidate_states_arguments:
    mdin_intermidate_config: inter.yaml #intermidate mdins required states 3-8
    igb_solvent: 2 #igb [1,2,3,7,8]
    temperature: 298
    exponent_conformational_forces: [-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4] # list exponent values p 
    exponent_orientational_forces: [-4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8] # list exponent values p 
    restraint_type: 2 # choices: [ 1: CoM-CoM, 2: CoM-Heavy_Atom, 3: Heavy_Atom-Heavy_Atom, must be 1, 2 or 3 ]
    
    guest_restraint_template: /nas0/mbarton/simrun-CB7-3D-RISM_NEW-CYCLE/RESTRAINTS_ARCHIVE/freeze_restraints_folder_010322/rep0/cb7-mol01_ligand_restraint.FRST
    
    receptor_restraint_template: /nas0/mbarton/simrun-CB7-3D-RISM_NEW-CYCLE/RESTRAINTS_ARCHIVE/freeze_restraints_folder_010322/rep0/cb7-mol01_receptor_restraint.FRST
    
    complex_orientational_template: /nas0/mbarton/simrun-CB7-3D-RISM_NEW-CYCLE/RESTRAINTS_ARCHIVE/orientational_restraints_folder_010322/rep0/cb7-mol01_orientational_restraint.RST
    complex_conformational_template: /nas0/mbarton/simrun-CB7-3D-RISM_NEW-CYCLE/RESTRAINTS_ARCHIVE/freeze_restraints_folder_010322/rep0/cb7-mol01_complex_restraint.FRST