hardware_parameters:
    executable: "pmemd.MPI" # executable machine for MD choice : [sander, sander.MPI, pmemd, pmemd.MPI, pmeded.CUDA]
    mpi_command: srun # system dependent /
    CUDA:  # run on GPU
    output_directory_name: basic_md_dir

endstate_parameter_files:
    complex_parameter_filename: script_examples/structs/cb7-mol01_Hmass.parm7 # path to topology file; ["path/to/complex.parm7"]
    complex_coordinate_filename: script_examples/structs/cb7-mol01.rst7 # path to coordinate ["path/to/complex.ncrst"]list of coordinate file of a complex

number_of_cores_per_system:
  complex_ncores: 2 #total number of cores per job
  ligand_ncores: 1 #total number of cores per ligand simulation
  receptor_ncores: 1 #total number of cores per ligand simulation

AMBER_masks:
  receptor_mask: ":CB7" # list of Amber masks denoting receptor atoms in respected complex file
  ligand_mask: ":M01" # list of Amber masks denoting ligand atoms in respected complex file

workflow:
  endstate_method: basic_md #options REMD or 0 (meaning no endstate simulation will be performed just intermidates)endstate_method: REMD #options REMD, MD or 0 (meaning no endstate simulation will be performed just intermidates) 
  endstate_arguments:
      md_template_mdin: script_examples/endstate_templates_required/basic_md.template
  intermediate_states_arguments:
      mdin_intermediate_file: script_examples/four_fento_time_step_mdin_template.mdin #intermediate mdins required states 3-8
      igb_solvent: 2 #igb [1,2,3,7,8]
      temperature: 300
      exponent_conformational_forces: [-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 2.584963, 3, 3.584963, 4]  # list exponent values 2**p 
      exponent_orientational_forces: [-4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 6.584963, 7, 7.584963, 8]  # list exponent values 2**p 
      restraint_type: 2 # choices: [ 1: CoM-CoM, 2: CoM-Heavy_Atom, 3: Heavy_Atom-Heavy_Atom, must be 1, 2 or 3 ]